[package]
name = "hyperx-ngenuity-open"
version = "0.2.10"
edition = "2021"
authors = ["serejaishkin"]
license = "MIT"
repository = "https://github.com/serejaishkin/HyperHeadset_v2"

[dependencies]
hidapi = "2.6"
enigo = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
image = { version = "0.25", default-features = false, features = ["png"] }
rodio = { version = "0.19", default-features = false, features = ["wav"] }
reqwest = { version = "0.12", features = ["json"] }
tokio-tungstenite = { version = "0.23", features = ["native-tls"] }
futures-util = "0.3"
discord-rich-presence = "0.2"
serde_json = "1.0"
parking_lot = "0.12"
tray-icon = "0.19"
tokio = { version = "1.53.1", features = ["full"] }
lazy_static = "1.5.0"
eframe = "0.29"
egui = "0.29"
notify-rust = "4.11"
ksni = { version = "0.2", optional = true }
rfd = "0.15"
global-hotkey = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.56"
windows = { version = "0.58", features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libpulse-binding = "2.28"
ksni = "0.2"

[features]
embedded-voice = []

[[bin]]
name = "hyperx_ngenuity_open"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
