//! Windows Equalizer APO integration
use std::path::PathBuf;
use std::fs;

const APO_CONFIG_PATH: &str = r"C:\Program Files\EqualizerAPO\config\config.txt";
const APO_PRESETS_DIR: &str = r"C:\Program Files\EqualizerAPO\config\presets";

const BAND_FREQUENCIES: [f32; 10] = [
    32.0, 64.0, 125.0, 250.0, 500.0,
    1000.0, 2000.0, 4000.0, 8000.0, 16000.0,
];

pub fn is_apo_installed() -> bool {
    PathBuf::from(APO_CONFIG_PATH).parent().map(|p| p.exists()).unwrap_or(false)
}

pub fn apply_eq_bands(bands: &[f32; 10]) -> anyhow::Result<()> {
    if !is_apo_installed() {
        return Err(anyhow::anyhow!("Equalizer APO not found at {}", APO_CONFIG_PATH));
    }
    let mut config = String::from("; Generated by HyperX NGENUITY Open\n");
    config.push_str("; Do not edit manually\n");
    config.push_str("Preamp: -6 dB\n\n");
    for (freq, gain) in BAND_FREQUENCIES.iter().zip(bands.iter()) {
        config.push_str(&format!("Filter: ON PK Fc {:.0} Hz Gain {:.1} dB Q 1.41\n", freq, gain));
    }
    fs::write(APO_CONFIG_PATH, config)?;
    log::info!("[WindowsEQ] Applied {} bands to Equalizer APO", bands.len());
    Ok(())
}

pub fn save_preset(name: &str, bands: &[f32; 10]) -> anyhow::Result<()> {
    let preset_dir = PathBuf::from(APO_PRESETS_DIR);
    if !preset_dir.exists() { fs::create_dir_all(&preset_dir)?; }
    let path = preset_dir.join(format!("hyperx_{}.txt", name.to_lowercase().replace(" ", "_")));
    let mut content = String::from("; HyperX preset\n");
    content.push_str("Preamp: -6 dB\n\n");
    for (freq, gain) in BAND_FREQUENCIES.iter().zip(bands.iter()) {
        content.push_str(&format!("Filter: ON PK Fc {:.0} Hz Gain {:.1} dB Q 1.41\n", freq, gain));
    }
    fs::write(&path, content)?;
    log::info!("[WindowsEQ] Saved preset to {:?}", path);
    Ok(())
}

pub fn load_preset(name: &str) -> anyhow::Result<[f32; 10]> {
    let path = PathBuf::from(APO_PRESETS_DIR).join(format!("hyperx_{}.txt", name.to_lowercase().replace(" ", "_")));
    let content = fs::read_to_string(&path)?;
    let mut bands = [0.0f32; 10];
    let mut idx = 0;
    for line in content.lines() {
        if line.starts_with("Filter:") && idx < 10 {
            if let Some(gain_part) = line.split("Gain ").nth(1) {
                if let Some(gain_str) = gain_part.split(" dB").next() {
                    if let Ok(gain) = gain_str.parse::<f32>() { bands[idx] = gain; idx += 1; }
                }
            }
        }
    }
    if idx != 10 { return Err(anyhow::anyhow!("Preset file corrupted")); }
    log::info!("[WindowsEQ] Loaded preset from {:?}", path);
    Ok(bands)
}

pub fn list_presets() -> Vec<String> {
    let preset_dir = PathBuf::from(APO_PRESETS_DIR);
    if !preset_dir.exists() { return Vec::new(); }
    let mut presets = Vec::new();
    if let Ok(entries) = fs::read_dir(&preset_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("hyperx_") && name.ends_with(".txt") {
                let preset = name.trim_start_matches("hyperx_").trim_end_matches(".txt").replace("_", " ");
                presets.push(preset);
            }
        }
    }
    presets
}