window.I18N = {
  ru: {
    'sidebar.mic_on': 'МИКР ВКЛ',
    'sidebar.mic_off': 'МИКР ВЫКЛ',
    'sidebar.sidetone': 'Сайдтон',
    'sidebar.play': 'ИГРАТЬ',
    'tab.dashboard': 'Главная',
    'tab.equalizer': 'Эквалайзер',
    'tab.settings': 'Настройки',
    'header.searching': 'ПОИСК',
    'header.connected': 'ВКЛ',
    'header.disconnected': 'ВЫКЛ',
    'header.battery': '[БАТ]',
    'header.compact_title': 'Компактный режим',
    'dash.active_headset': 'Активная гарнитура:',
    'dash.title': 'Состояние гарнитуры',
    'dash.battery': 'Батарея:',
    'dash.microphone': 'Микрофон:',
    'dash.signal': 'Сигнал:',
    'dash.searching': 'Поиск устройства...',
    'dash.quick_actions': 'Быстрые действия',
    'dash.mute_mic': 'Выкл. микрофон',
    'dash.check_battery': 'Проверить батарею (голос)',
    'dash.searching_headset': 'Поиск гарнитуры...',
    'dash.connect_text': 'Подключите гарнитуру/донгл HyperX для начала. Обнаружение работает автоматически.',
    'dash.retry': 'Повторить',
    'dash.disconnected_title': 'Гарнитура отключена',
    'dash.disconnected_text': 'Ожидание устройства...',
    'dash.connected_title': 'Гарнитура подключена',
    'dash.connected_text': 'Устройство готово',
    'dash.charging_text': 'Зарядка...',
    'eq.title': 'Эквалайзер',
    'eq.preset': 'Пресет',
    'eq.preset_flat': 'Плоский',
    'eq.preset_bass_boost': 'Усиление басов',
    'eq.preset_bass_cut': 'Ослабление басов',
    'eq.preset_treble_boost': 'Усиление верхних',
    'eq.preset_voice_chat': 'Голосовой чат',
    'eq.preset_gaming': 'Игры',
    'eq.reset': 'Сбросить',
    'eq.apply': 'Применить',
    'eq.note': 'На Windows эквалайзер записывается в Equalizer APO. На Linux/macOS пресет сохраняется в конфиге.',
    'eq.save_per_device': 'Сохранить как пресет гарнитуры',
    'eq.clear_per_device': 'Удалить пресет гарнитуры',
    'eq.active_for': 'Персональный пресет эквалайзера активен для',
    'eq.using_global': 'Используется глобальный эквалайзер для',
    'settings.title': 'Настройки',
    'settings.subtitle': 'Настройки из оригинального приложения.',
    'settings.saved': 'Сохранено',
    'settings.unsaved': 'Несохранённые изменения',
    'settings.save_msg': 'Изменения сохранены в config.toml и tray_icon.toml',
    'settings.unsaved_msg': 'Есть несохранённые изменения',
    'settings.tab_headset': 'Гарнитура',
    'settings.tab_voice': 'Голос',
    'settings.tab_tray': 'Иконка в трее',
    'settings.tab_discord': 'Discord',
    'settings.tab_debug': 'Отладка',
    'settings.tab_interface': 'Интерфейс',
    'headset.section': 'Гарнитура',
    'headset.enabled': 'Приложение включено',
    'headset.enabled_desc': 'Включить управление HyperHeadset',
    'headset.sidetone': 'Сайдтон',
    'headset.sidetone_desc': 'Слышать свой микрофон в гарнитуре',
    'headset.voice_prompts': 'Голосовые подсказки',
    'headset.voice_prompts_desc': 'Запомнить настройку голосовых подсказок гарнитуры',
    'headset.auto_shutdown': 'Авто-выключение',
    'headset.auto_shutdown_desc': '0 — таймер выключен',
    'headset.mute_button': 'Кнопка мьюта',
    'headset.mode': 'Режим',
    'headset.mode_desc': 'Поведение кнопки гарнитуры',
    'headset.mode_standard': 'Стандартный (Микр.мьют)',
    'headset.mode_play_pause': 'Воспр./Пауза',
    'headset.mode_smart_double': 'Умный: одно нажатие — мьют / двойное — воспр./пауза',
    'headset.mode_smart_hold': 'Умный: короткое — воспр./пауза / удержание — мьют',
    'headset.mode_hold_play_pause': 'Умный: короткое — мьют / удержание — воспр./пауза',
    'headset.keybind': 'Бинд',
    'headset.keybind_desc': 'Глобальный мьют/клавиша Discord',
    'headset.double_tap': 'Задержка двойного нажатия',
    'headset.double_tap_desc': 'Интервал умного двойного клика',
    'voice.section_bundled': 'Встроенные WAV-голоса',
    'voice.bundled_note': 'Проект содержит все голосовые подсказки батареи от bat_000.wav до bat_100.wav (0% до 100%), а также WAV-файлы зарядки, полной зарядки и низкого заряда батареи.',
    'voice.enabled': 'Включить голос',
    'voice.enabled_desc': 'Включить голосовые уведомления о батарее/статусе',
    'voice.battery_low': 'Батарея разряжена',
    'voice.battery_low_desc': 'Воспроизвести low_battery.wav',
    'voice.charging': 'Зарядка',
    'voice.charging_desc': 'Воспроизвести charging.wav',
    'voice.full_charge': 'Полная зарядка',
    'voice.full_charge_desc': 'Воспроизвести full_charge.wav',
    'voice.on_connect': 'Уведомление о подключении',
    'voice.on_connect_desc': 'Используются только доступные голосовые события',
    'voice.on_disconnect': 'Уведомление об отключении',
    'voice.on_disconnect_desc': 'Используются только доступные голосовые события',
    'voice.button_check': 'Проверка кнопки',
    'voice.button_check_desc': 'Разрешить проверку батареи (голос)',
    'voice.clip_mode': 'Режим клипа батареи',
    'voice.clip_mode_desc': 'Используется ближайший встроенный клип',
    'voice.test': 'Тест встроенных WAV',
    'voice.section_custom': 'Пользовательский голосовой пакет',
    'voice.custom_note': 'Загрузите свои WAV-файлы (bat_000.wav ... bat_100.wav, charging.wav, full_charge.wav, low_battery.wav) в папку или загрузите через интерфейс ниже.',
    'voice.custom_folder': 'Папка с голосами',
    'voice.custom_folder_desc': 'Путь к папке с пользовательскими WAV',
    'voice.upload': 'Загрузить WAV файл',
    'tray.section': 'Иконка в трее — Превью',
    'tray.mode': 'Режим',
    'tray.mode_desc': 'Большой: крупные цифры / Цифры: стилизованная иконка',
    'tray.mode_big': 'Большой (крупные цифры)',
    'tray.mode_digits': 'Цифры (стилизованная иконка)',
    'tray.icon_size': 'Размер иконки',
    'tray.icon_size_desc': 'Разрешение превью',
    'tray.font_scale': 'Масштаб шрифта',
    'tray.outline': 'Ширина обводки',
    'tray.border': 'Ширина рамки',
    'tray.gap': 'Расстояние между цифрами',
    'tray.colors': 'Цвета: ФОН / ТЕКСТ / ОБВОДКА / РАМКА',
    'tray.color_charging': 'Зарядка',
    'tray.color_high': 'Высокий',
    'tray.color_medium': 'Средний',
    'tray.color_low': 'Низкий',
    'discord.section': 'Discord',
    'discord.mode': 'Режим',
    'discord.mode_desc': 'Режим интеграции Discord',
    'discord.mode_none': 'Нет',
    'discord.mode_keybind': 'Клавиша привязки',
    'discord.mode_direct': 'Прямой',
    'discord.keybind': 'Клавиша привязки',
    'discord.keybind_desc': 'Клавиша мьюта Discord',
    'discord.app_id': 'ID приложения',
    'discord.app_id_desc': 'ID приложения Discord Rich Presence',
    'discord.show_battery': 'Показывать батарею',
    'discord.show_mute': 'Показывать статус мьюта',
    'debug.section': 'Отладка и логирование',
    'debug.logging': 'Отладочный лог',
    'debug.logging_desc': 'Подробные логи Rust',
    'debug.console': 'Лог в консоль',
    'debug.file': 'Лог в файл',
    'debug.file_desc': 'Записывать hyperx-ngenuity-open.log',
    'interface.section': 'Интерфейс и запуск',
    'interface.start_os': 'Запускать с системой',
    'interface.start_os_desc': 'Запускаться автоматически при загрузке ОС',
    'interface.start_compact': 'Запускать в компактном режиме',
    'interface.start_compact_desc': 'Открывать компактное окно автоматически после запуска',
    'interface.compact_mode': 'Компактный режим',
    'interface.compact_mode_desc': 'Запоминать состояние компактного режима',
    'interface.language': 'Язык',
    'interface.updates': 'Обновления',
    'interface.check_updates': 'Проверить обновления',
    'save.reload': 'Перезагрузить',
    'save.save': 'Сохранить настройки',
    'toast.settings_saved': 'Настройки сохранены',
    'toast.voice_test': 'Тест встроенного WAV запущен',
    'toast.voice_error': 'Ошибка теста',
    'toast.autostart_on': 'Автозапуск включён',
    'toast.autostart_off': 'Автозапуск выключен',
    'toast.update_checking': 'Проверка обновлений...',
    'toast.up_to_date': 'У вас последняя версия',
    'toast.downloading': 'Скачивание обновления',
    'toast.update_error': 'Ошибка проверки обновлений',
    'toast.eq_applied': 'Эквалайзер применён',
    'toast.device_switch_error': 'Ошибка переключения устройства',
    'toast.no_device': 'Нет подключённого устройства',
    'toast.eq_saved': 'Пресет гарнитуры сохранён',
    'toast.eq_removed': 'Пресет гарнитуры удалён',
    'toast.voice_folder_saved': 'Папка голосов сохранена',
    'toast.uploaded': 'Загружен',
    'toast.upload_error': 'Ошибка загрузки',
    'toast.battery_voice_played': 'Голосовое уведомление о батарее воспроизведено',
    'toast.voice_check_error': 'Ошибка проверки',
    'toast.save_error': 'Ошибка сохранения',
    'toast.load_error': 'Ошибка загрузки настроек',
    'toast.mute_toggled': 'Состояние мьюта изменено',
    'toast.device_cmd_error': 'Ошибка команды устройства',
    'toast.unsupported': 'Обновлятель недоступен',
    'conn.on': 'ВКЛ',
    'conn.off': 'ВЫКЛ',
    'conn.searching': 'ПОИСК',
    'bat.charging': 'Зарядка',
    'bat.battery': 'Батарея',
    'bat.no_connection': 'Нет подключения',
    'bat.active': 'Активен',
    'bat.muted': 'Выключен',
    'bat.inactive': 'Неактивен',
    'mic.on': 'МИКР ВКЛ',
    'mic.off': 'МИКР ВЫКЛ',
    'compact.mute': 'Мьют',
    'compact.main': 'Основное',
  },
  en: {
    'sidebar.mic_on': 'MIC ON',
    'sidebar.mic_off': 'MIC OFF',
    'sidebar.sidetone': 'Sidetone',
    'sidebar.play': 'PLAY',
    'tab.dashboard': 'Dashboard',
    'tab.equalizer': 'Equalizer',
    'tab.settings': 'Settings',
    'header.searching': 'SEARCHING',
    'header.connected': 'ON',
    'header.disconnected': 'OFF',
    'header.battery': '[BAT]',
    'header.compact_title': 'Compact mode',
    'dash.active_headset': 'Active headset:',
    'dash.title': 'Headset status',
    'dash.battery': 'Battery:',
    'dash.microphone': 'Microphone:',
    'dash.signal': 'Signal:',
    'dash.searching': 'Searching for device...',
    'dash.quick_actions': 'Quick actions',
    'dash.mute_mic': 'Mute microphone',
    'dash.check_battery': 'Check battery (voice)',
    'dash.searching_headset': 'Searching for headset...',
    'dash.connect_text': 'Connect your HyperX headset/dongle to start. Detection works automatically.',
    'dash.retry': 'Retry',
    'dash.disconnected_title': 'Headset disconnected',
    'dash.disconnected_text': 'Waiting for device...',
    'dash.connected_title': 'Headset connected',
    'dash.connected_text': 'Device ready',
    'dash.charging_text': 'Charging...',
    'eq.title': 'Equalizer',
    'eq.preset': 'Preset',
    'eq.preset_flat': 'Flat',
    'eq.preset_bass_boost': 'Bass boost',
    'eq.preset_bass_cut': 'Bass cut',
    'eq.preset_treble_boost': 'Treble boost',
    'eq.preset_voice_chat': 'Voice chat',
    'eq.preset_gaming': 'Gaming',
    'eq.reset': 'Reset',
    'eq.apply': 'Apply',
    'eq.note': 'On Windows the equalizer is written to Equalizer APO. On Linux/macOS the preset is saved in config.',
    'eq.save_per_device': 'Save as headset preset',
    'eq.clear_per_device': 'Delete headset preset',
    'eq.active_for': 'Personal EQ preset active for',
    'eq.using_global': 'Using global equalizer for',
    'settings.title': 'Settings',
    'settings.subtitle': 'Settings from the original application.',
    'settings.saved': 'Saved',
    'settings.unsaved': 'Unsaved changes',
    'settings.save_msg': 'Changes saved to config.toml and tray_icon.toml',
    'settings.unsaved_msg': 'There are unsaved changes',
    'settings.tab_headset': 'Headset',
    'settings.tab_voice': 'Voice',
    'settings.tab_tray': 'Tray icon',
    'settings.tab_discord': 'Discord',
    'settings.tab_debug': 'Debug',
    'settings.tab_interface': 'Interface',
    'headset.section': 'Headset',
    'headset.enabled': 'Application enabled',
    'headset.enabled_desc': 'Enable HyperHeadset control',
    'headset.sidetone': 'Sidetone',
    'headset.sidetone_desc': 'Hear your microphone in the headset',
    'headset.voice_prompts': 'Voice prompts',
    'headset.voice_prompts_desc': 'Remember headset voice prompts setting',
    'headset.auto_shutdown': 'Auto shutdown',
    'headset.auto_shutdown_desc': '0 — timer disabled',
    'headset.mute_button': 'Mute button',
    'headset.mode': 'Mode',
    'headset.mode_desc': 'Headset button behavior',
    'headset.mode_standard': 'Standard (Mic mute)',
    'headset.mode_play_pause': 'Play/Pause',
    'headset.mode_smart_double': 'Smart: single tap — mute / double — play/pause',
    'headset.mode_smart_hold': 'Smart: short — play/pause / hold — mute',
    'headset.mode_hold_play_pause': 'Smart: short — mute / hold — play/pause',
    'headset.keybind': 'Keybind',
    'headset.keybind_desc': 'Global mute/Discord key',
    'headset.double_tap': 'Double tap delay',
    'headset.double_tap_desc': 'Smart double click interval',
    'voice.section_bundled': 'Built-in WAV voices',
    'voice.bundled_note': 'The project contains all battery voice prompts from bat_000.wav to bat_100.wav (0% to 100%), as well as WAV files for charging, full charge and low battery.',
    'voice.enabled': 'Enable voice',
    'voice.enabled_desc': 'Enable battery/status voice notifications',
    'voice.battery_low': 'Battery low',
    'voice.battery_low_desc': 'Play low_battery.wav',
    'voice.charging': 'Charging',
    'voice.charging_desc': 'Play charging.wav',
    'voice.full_charge': 'Full charge',
    'voice.full_charge_desc': 'Play full_charge.wav',
    'voice.on_connect': 'Connection notification',
    'voice.on_connect_desc': 'Only available voice events are used',
    'voice.on_disconnect': 'Disconnection notification',
    'voice.on_disconnect_desc': 'Only available voice events are used',
    'voice.button_check': 'Button check',
    'voice.button_check_desc': 'Allow battery check (voice)',
    'voice.clip_mode': 'Battery clip mode',
    'voice.clip_mode_desc': 'Nearest built-in clip is used',
    'voice.test': 'Test built-in WAV',
    'voice.section_custom': 'Custom voice pack',
    'voice.custom_note': 'Upload your WAV files (bat_000.wav ... bat_100.wav, charging.wav, full_charge.wav, low_battery.wav) to a folder or upload via the interface below.',
    'voice.custom_folder': 'Voice folder',
    'voice.custom_folder_desc': 'Path to folder with custom WAV files',
    'voice.upload': 'Upload WAV file',
    'tray.section': 'Tray icon — Preview',
    'tray.mode': 'Mode',
    'tray.mode_desc': 'Big: large digits / Digits: styled icon',
    'tray.mode_big': 'Big (large digits)',
    'tray.mode_digits': 'Digits (styled icon)',
    'tray.icon_size': 'Icon size',
    'tray.icon_size_desc': 'Preview resolution',
    'tray.font_scale': 'Font scale',
    'tray.outline': 'Outline width',
    'tray.border': 'Border width',
    'tray.gap': 'Gap between digits',
    'tray.colors': 'Colors: BG / FG / OUTLINE / BORDER',
    'tray.color_charging': 'Charging',
    'tray.color_high': 'High',
    'tray.color_medium': 'Medium',
    'tray.color_low': 'Low',
    'discord.section': 'Discord',
    'discord.mode': 'Mode',
    'discord.mode_desc': 'Discord integration mode',
    'discord.mode_none': 'None',
    'discord.mode_keybind': 'Keybind',
    'discord.mode_direct': 'Direct',
    'discord.keybind': 'Keybind',
    'discord.keybind_desc': 'Discord mute key',
    'discord.app_id': 'Application ID',
    'discord.app_id_desc': 'Discord Rich Presence application ID',
    'discord.show_battery': 'Show battery',
    'discord.show_mute': 'Show mute status',
    'debug.section': 'Debug and logging',
    'debug.logging': 'Debug log',
    'debug.logging_desc': 'Verbose Rust logs',
    'debug.console': 'Log to console',
    'debug.file': 'Log to file',
    'debug.file_desc': 'Write hyperx-ngenuity-open.log',
    'interface.section': 'Interface and startup',
    'interface.start_os': 'Start with system',
    'interface.start_os_desc': 'Auto-start on OS boot',
    'interface.start_compact': 'Start in compact mode',
    'interface.start_compact_desc': 'Open compact window automatically after launch',
    'interface.compact_mode': 'Compact mode',
    'interface.compact_mode_desc': 'Remember compact mode state',
    'interface.language': 'Language',
    'interface.updates': 'Updates',
    'interface.check_updates': 'Check for updates',
    'save.reload': 'Reload',
    'save.save': 'Save settings',
    'toast.settings_saved': 'Settings saved',
    'toast.voice_test': 'Built-in WAV test started',
    'toast.voice_error': 'Test error',
    'toast.autostart_on': 'Autostart enabled',
    'toast.autostart_off': 'Autostart disabled',
    'toast.update_checking': 'Checking for updates...',
    'toast.up_to_date': 'You have the latest version',
    'toast.downloading': 'Downloading update',
    'toast.update_error': 'Update check error',
    'toast.eq_applied': 'Equalizer applied',
    'toast.device_switch_error': 'Device switch error',
    'toast.no_device': 'No device connected',
    'toast.eq_saved': 'Headset preset saved',
    'toast.eq_removed': 'Headset preset deleted',
    'toast.voice_folder_saved': 'Voice folder saved',
    'toast.uploaded': 'Uploaded',
    'toast.upload_error': 'Upload error',
    'toast.battery_voice_played': 'Battery voice notification played',
    'toast.voice_check_error': 'Check error',
    'toast.save_error': 'Save error',
    'toast.load_error': 'Settings load error',
    'toast.mute_toggled': 'Mute state changed',
    'toast.device_cmd_error': 'Device command error',
    'toast.unsupported': 'Updater unavailable',
    'conn.on': 'ON',
    'conn.off': 'OFF',
    'conn.searching': 'SEARCHING',
    'bat.charging': 'Charging',
    'bat.battery': 'Battery',
    'bat.no_connection': 'No connection',
    'bat.active': 'Active',
    'bat.muted': 'Muted',
    'bat.inactive': 'Inactive',
    'mic.on': 'MIC ON',
    'mic.off': 'MIC OFF',
    'compact.mute': 'Mute',
    'compact.main': 'Main',
  },
};

window.__currentLang = 'ru';

window.applyLanguage = function (lang) {
  window.__currentLang = lang;
  const dict = window.I18N[lang];
  if (!dict) return;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (key && dict[key] !== undefined) {
      if (el.tagName === 'OPTION') {
        el.textContent = dict[key];
      } else if (el.children.length > 0) {
        // For elements with children (labels with inputs), only update text nodes
        for (const node of el.childNodes) {
          if (node.nodeType === Node.TEXT_NODE && node.textContent.trim()) {
            node.textContent = ' ' + dict[key] + ' ';
            break;
          }
        }
      } else {
        el.textContent = dict[key];
      }
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (key && dict[key] !== undefined) {
      el.placeholder = dict[key];
    }
  });

  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    if (key && dict[key] !== undefined) {
      el.title = dict[key];
    }
  });
};
