name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libhidapi-dev libusb-1.0-0-dev libudev-dev libasound2-dev pkg-config
      - name: Build (with voice)
        run: cargo build --verbose
      - name: Build (without voice)
        run: cargo build --verbose --no-default-features
      - name: Test
        run: cargo test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test
